# Generated by Django 5.1.4 on 2025-01-11 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0015_reserve_paid'),
        ('room', '0005_alter_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupied',
        ),
        migrations.AddField(
            model_name='room',
            name='occupied_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='room',
            name='reservations',
            field=models.ManyToManyField(blank=True, to='reservation_app.reserve'),
        ),
    ]
