# Generated by Django 5.1.5 on 2025-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_room_occupied_room_occupied_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, default='rooms/default.jpg', null=True, upload_to='rooms'),
        ),
    ]
