# Generated by Django 5.1.4 on 2024-12-26 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.reserve')),
            ],
        ),
    ]
