# Generated by Django 5.1.3 on 2024-12-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_alter_reserve_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='phone',
        ),
    ]
