# Generated by Django 5.1.3 on 2024-12-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0003_remove_reserve_email_remove_reserve_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='days',
            new_name='nights',
        ),
    ]
