# Generated by Django 5.1.3 on 2024-12-30 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0004_rename_days_reserve_nights'),
        ('room', '0005_alter_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
