# Generated by Django 5.1.3 on 2024-12-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0005_reserve_end_date_alter_reserve_room'),
        ('room', '0005_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
