# Generated by Django 5.1.3 on 2024-12-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0006_alter_reserve_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
