# Generated by Django 5.1.3 on 2024-12-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0007_reserve_confirmed_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='room',
            new_name='rooms',
        ),
    ]
