# Generated by Django 5.1.3 on 2024-12-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0008_rename_room_reserve_rooms'),
        ('room', '0005_alter_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='rooms',
        ),
        migrations.AddField(
            model_name='reserve',
            name='rooms',
            field=models.ManyToManyField(to='room.room'),
        ),
    ]
