# Generated by Django 5.1.3 on 2024-12-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0009_remove_reserve_rooms_reserve_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
