# Generated by Django 5.1.3 on 2024-12-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0010_reserve_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
