# Generated by Django 5.1.3 on 2025-01-02 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0013_reserve_user_alter_image_image_alter_reserve_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='images',
            field=models.ManyToManyField(max_length=models.IntegerField(), related_name='image_set', to='reservation_app.image'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
