# Generated by Django 5.1.4 on 2025-01-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0014_alter_reserve_images_alter_reserve_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
