# Generated by Django 5.1.4 on 2025-01-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0015_reserve_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='confirmed',
        ),
    ]
