# Generated by Django 5.1.4 on 2025-01-11 12:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0016_remove_reserve_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='occupied_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None),
        ),
    ]
