# Generated by Django 5.1.5 on 2025-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0017_reserve_occupied_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
