# Generated by Django 5.1.5 on 2025-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0018_alter_reserve_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
